apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: argocd-mcp
        image: python:3.11-slim   # <-- no custom docker
        command: ["sh", "-c"]
        args:
          - pip install fastapi uvicorn[standard] requests python-dotenv urllib3 mcp \
            && uvicorn server:app --host 0.0.0.0 --port 8000
        workingDir: /app
        volumeMounts:
        - name: server-code
          mountPath: /app
        ports:
        - containerPort: 8000
      volumes:
      - name: server-code
        configMap:
          name: argocd-mcp-code
