apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-mcp-server.fullname" . }}
  labels:
{{ include "argocd-mcp-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argocd-mcp-server
  template:
    metadata:
      labels:
        app: argocd-mcp-server
    spec:
      serviceAccountName: {{ include "argocd-mcp-server.fullname" . }}-sa

      # Init container installs uvicorn and fastapi in a writable volume
      initContainers:
        - name: install-uvicorn
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args: ["pip install --no-cache-dir uvicorn fastapi -t /python-packages"]
          volumeMounts:
            - name: python-packages
              mountPath: /python-packages

      containers:
        - name: mcp-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args: ["PYTHONPATH=/python-packages uvicorn server:app --host 0.0.0.0 --port 8000 --reload"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ include "argocd-mcp-server.fullname" . }}-env
          env:
            - name: APP_MODULE
              value: "server:app"
            - name: PORT
              value: "8000"
          volumeMounts:
            - name: server-code
              mountPath: /app/server.py
              subPath: server.py
            - name: tools-json
              mountPath: /app/tools.json
              subPath: tools.json
            - name: python-packages
              mountPath: /python-packages

      volumes:
        - name: server-code
          configMap:
            name: {{ include "argocd-mcp-server.fullname" . }}-server
        - name: tools-json
          configMap:
            name: {{ include "argocd-mcp-server.fullname" . }}-tools
        - name: python-packages
          emptyDir: {}
