apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-mcp-server.fullname" . }}
  labels:
{{ include "argocd-mcp-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argocd-mcp-server
  template:
    metadata:
      labels:
        app: argocd-mcp-server
    spec:
      serviceAccountName: {{ include "argocd-mcp-server.fullname" . }}-sa
      containers:
        - name: mcp-server
          image: "tiangolo/uvicorn-gunicorn-fastapi:python3.11"
          command: ["/bin/sh", "-c"]
          args:
            - pip install requests && exec /start.sh
          imagePullPolicy: IfNotPresent
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: {{ include "argocd-mcp-server.fullname" . }}-env
          env:
            - name: APP_MODULE
              value: "server:app"   # <--- tells uvicorn which app to start
            - name: PORT
              value: "8000"         # <--- ensures it listens on 0.0.0.0:8000
          volumeMounts:
            - name: server-code
              mountPath: /app/server.py
              subPath: server.py
            - name: tools-json
              mountPath: /app/tools.json
              subPath: tools.json
      volumes:
        - name: server-code
          configMap:
            name: {{ include "argocd-mcp-server.fullname" . }}-server
        - name: tools-json
          configMap:
            name: {{ include "argocd-mcp-server.fullname" . }}-tools
