apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-mcp-server.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{ (.Files.Get "files/.env" | indent 2) }}
