apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-mcp-server.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80                # what the ELB listens on
      targetPort: 8000        # containerPort inside your pod
      protocol: TCP
      name: http
  selector:
    app: argocd-mcp-server
